@startuml
'https://plantuml.com/class-diagram
title 单例模式
class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - strategy:Strategy
    -{static}instance:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    +getinstance(int locationX, int locationY, int speedX, int speedY, int hp);
}
class user
{
}
note left of HeroAircraft::getinstance
    public  static HeroAircraft getInstance(int locationX, int locationY, int speedX, int speedY, int hp)
    {
        if(instance==null)
        {synchronized (HeroAircraft.class)
        {
            if(instance==null)
                instance=new HeroAircraft(locationX, locationY, speedX, speedY, hp);
        }
        }
        return instance;

    }
end note



HeroAircraft<-- user
@enduml