@startuml
'https://plantuml.com/class-diagram
title 单例模式
class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    -{static}instance:HeroAircraft
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    +getinstance(int locationX, int locationY, int speedX, int speedY, int hp);
}
class user
{
}




HeroAircraft<-- user
@enduml