@startuml
'https://plantuml.com/class-diagram

class Game
{
+{abstract} action():void
}
class EasyGame extends Game
{
+action():void
}
class OrdinaryGame extends Game
{
+action():void
}
class HardGame extends Game
{
+action():void
}


@enduml